# Generated by Django 4.2.8 on 2025-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='content',
        ),
        migrations.AddField(
            model_name='employee',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.TextField(),
        ),
    ]
