# Generated by Django 4.2.8 on 2025-08-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_remove_employee_content_employee_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.CharField(max_length=100),
        ),
    ]
