# Generated by Django 4.2.8 on 2025-08-25 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(limit_value=50, message='The Todo is too long !')]),
        ),
    ]
