# Generated by Django 4.2.8 on 2025-08-26 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=25, validators=[django.core.validators.MaxLengthValidator(limit_value=25)]),
        ),
    ]
