# Generated by Django 4.2.8 on 2025-08-27 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_alter_todo_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='author',
            field=models.CharField(default='Admin', max_length=25, validators=[django.core.validators.MaxLengthValidator(limit_value=25)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MaxLengthValidator(limit_value=25)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profession',
            field=models.CharField(max_length=25, validators=[django.core.validators.MaxLengthValidator(limit_value=25)]),
        ),
    ]
