# Generated by Django 4.2.8 on 2025-08-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0011_alter_employee_author_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=25),
        ),
    ]
